name: Deploy

on:

  push:
    branches: [ main ]


jobs:

  build:
   
    runs-on: ubuntu-latest

    
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/html/
          git pull origin main
          git status
          
